# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"
  model_name: "UNET"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 512 #16
  use_norm: True
  init_size: 1
   #16


###################
## Dataset options
dataset_params:
  training_size: 19132
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/semantic-kitti.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "/media/wasfy/One\ Touch/TA/drive/All/omarwasfy/Master/Thesis/Datasets/dataset/sequences/"
  imageset: "train"
  return_ref: True
  batch_size: 1
  shuffle: True
  num_workers: 12 #4

val_data_loader:
  data_path: "/media/wasfy/One\ Touch/TA/drive/All/omarwasfy/Master/Thesis/Datasets/dataset/sequences/"
  imageset: "val" #"val"
  return_ref: True
  batch_size: 1
  shuffle: True
  num_workers: 12 #4


###################
## Train params
train_params:
  model_load_path: "./model_load_dir/model_tmp.pt"
  model_save_path: "./model_save_dir/model_tmp2.pt"
  checkpoint_every_n_steps: 49
  max_num_epochs: 20 #40
  eval_every_n_steps: 50 #4599
  learning_rate: 0.001 #1
  optimizer: SGD  # [SGD, Adam]
  lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-4
  lambda_seg2d: 1
  lambda_xm: 0.05
  decay_rate: 0.1
  decay_step: 20
  monitor: "val/mIoU"
  save_top_k: 10
  log_dir_name: "pl_logs"
  save_dir_path: "./model_save_dir"
  ckpt_path: "./model_save_dir/checkpoints/last.ckpt"
  load_ckpt: False
  swa_enabled: True
  swa_start: 10
  swa_annealing_epochs: 10
  swa_lr: 0.05
  log_every_n_steps: 50
  gradient_clip_val: 1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0
  patience: 10
